---
modules-search: [ local, @out@/lib/calamares/modules ]

instances:
  - module: nixos
    weight: 48

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - users
      - partition
      - summary
  - exec:
      - kwakcheck
      - partition
      - mount
      - nixos
      - users
      - umount
  - show:
      - finished

branding: kwakos
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
hide-back-and-next-during-exec: true
quit-at-end: false
