---
defaultGroups: [ users, networkmanager, wheel ]
autologinGroup: users
sudoersGroup: wheel
setRootPassword: true
doReusePassword: true
doAutologin: false
displayAutologin: false
passwordRequirements:
  minLength: 8
  maxLength: 64
allowWeakPasswords: true
allowWeakPasswordsDefault: false
user:
  shell: /run/current-system/sw/bin/bash
  forbidden_names: [ root, nixos, greeter, kwak-cards ]
hostname:
  location: None
  writeHostsFile: false
  forbidden_names: [ localhost ]
