{ hyprlax, fetchFromGitHub }:
hyprlax.overrideAttrs (old: {
  version = "2.2.7";
  src = fetchFromGitHub {
    owner = "sandwichfarm";
    repo = "hyprlax";
    tag = "v2.2.7";
    hash = "sha256-CkhHGPfYqGTPSFFzhOoIQCGi31wK7u+MYpWqeq55RJQ=";
  };
  # Upstream's normal build uses -march=native; keep the Nix artifact portable.
  makeFlags = (old.makeFlags or [ ]) ++ [ "CI=1" ];
  # Release archives omit the VERSION file normally generated by upstream CI.
  postPatch = (old.postPatch or "") + ''
    printf '%s\n' '2.2.7' > VERSION
  '';
  postInstall = (old.postInstall or "") + ''
    mkdir -p $out/share/hyprlax
    cp -r ${../config/hyprlax} $out/share/hyprlax/pixel-city
  '';
})
